### ISSUE TITLE
antigenic site annotation

### ISSUE THREAD

**Issue by tkanderson** [flu-crew/flutile#1]
It would be good to have the antigenic site annotation incorporated with the aadiff command - or as a separate option. Would this be possible by the next VCM meeting? Or - continue using excel lookup tables...

**Comment by arendsee** [comment]
@tkanderson It is quite doable. I think it would be reasonable to include any published sets of antigenic sites in the tool itself and also to allow custom tables. For example, we might have a `--caton82` flag for H1 and an `--annotation=myfile.tsv` annotation for your custom annotations. Each annotation could have its own column.
